apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: perception-pipeline-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: perception-pipeline
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type:               AverageUtilization
        averageUtilization: 70