apiVersion: v1
kind: Service
metadata:
  name: perception-pipeline-svc
spec:
  selector:
    app: perception-pipeline
  ports:
  - name: http
    port:       80
    targetPort: 8080
  - name: metrics
    port:       9090
    targetPort: 9090
  type: LoadBalancer